title: Aerium Improvement Proposals
description: >-
  AIPs, or Aerium Improvement Proposals, define standards and guidelines to
  improve the Aerium project.
  AIPs are designed to be a transparent and collaborative way to propose and
  discuss changes to the Aerium network.
url: "https://aips.aerium.dev"
baseurl: ""
github_username:  aerium-network
repository: aerium-network/aip

plugins:
  - jekyll-sitemap

jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

header_pages:
 - all.html
 - core.html
 - network.html
 - interface.html
 - informational.html
 - wallet.html

highlighter: rouge
markdown: kramdown
theme: minima
kramdown:
  parse_block_html: false
  auto_ids: true
  auto_id_stripping: true
  syntax_highlighter: rouge

permalink: /:slug

defaults:
  -
    scope:
      path: "AIPs"
    values:
      layout: "aip"

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - aip-template.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md

include:
  - LICENSE

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
