blank_issues_enabled: true
contact_links:
  - name: Do you want to discuss AIP ideas or ask questions about the process?
    url: https://discord.gg/H5vZkNnXCu
    about: Use the Fellowship of Aerium in discord for AIP discussion!
